/**
 * AI-generated activity marker module.
 *
 * Displays icons on course activities that were AI-generated by this plugin.
 * Icons are removed when activities are edited (tracked via event observer).
 *
 * @module     aiplacement_modgen/aigen_marker
 * @copyright  2025 Tom Cripps <tom.cripps@port.ac.uk>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

import Config from 'core/config';

/**
 * Initialize the AI-generated markers on the course page.
 *
 * @param {number} courseid The course ID
 */
export const init = (courseid) => {
    fetchAigenCmids(courseid)
        .then(cmids => {
            if (cmids && cmids.length > 0) {
                addMarkersToActivities(cmids);
            }
        })
        .catch(err => {
            // Silently fail - markers are optional UI enhancement
            window.console.warn('Failed to load AI-generated markers:', err);
        });
};

/**
 * Fetch the list of AI-generated course module IDs for a course.
 *
 * @param {number} courseid The course ID
 * @returns {Promise<number[]>} Array of cmids
 */
const fetchAigenCmids = async(courseid) => {
    const params = new URLSearchParams();
    params.append('courseid', courseid);
    params.append('sesskey', Config.sesskey);

    const response = await fetch(
        Config.wwwroot + '/ai/placement/modgen/ajax/get_aigen.php?' + params.toString()
    );

    if (!response.ok) {
        throw new Error('Failed to fetch AI-generated markers');
    }

    const data = await response.json();
    if (!data.success) {
        throw new Error(data.error || 'Unknown error');
    }

    return data.cmids || [];
};

/**
 * Add marker icons to AI-generated activities.
 *
 * @param {number[]} cmids Array of course module IDs to mark
 */
const addMarkersToActivities = (cmids) => {
    cmids.forEach(cmid => {
        // Find the activity element - li with data-for="cmitem"
        const activityEl = document.querySelector(`li[data-for="cmitem"][data-id="${cmid}"]`);
        if (!activityEl) {
            return;
        }

        // Find the activityname div
        const activityName = activityEl.querySelector('.activityname');
        if (!activityName) {
            return;
        }

        // Don't add duplicate markers
        if (activityName.querySelector('.aiplacement-modgen-aigen-marker')) {
            return;
        }

        // Create the marker
        const marker = document.createElement('span');
        marker.className = 'aiplacement-modgen-aigen-marker ms-1';
        const tooltipText = M.util.get_string('aigenmarker_tooltip', 'aiplacement_modgen');
        marker.setAttribute('title', tooltipText);
        // Safe: create icon element directly
const icon = document.createElement('i');
icon.className = 'fa fa-bolt text-info';
marker.innerHTML = '';
marker.appendChild(icon);

        // Append to activityname div
        activityName.appendChild(marker);
    });
};

export default {
    init
};
